**Numpy 기본 사용법**

Python의 Numpy 라이브러리는 List와 상호 변환이 가능합니다.

In [1]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소

3
int64
3


Python의 Numpy 라이브러리는 다양한 형태의 배열을 초기화 할 수 있습니다.

In [2]:
# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [3]:
# 0으로 초기화
array2 = np.zeros((4, 4), dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# 1로 초기화
array3 = np.ones((3, 3), dtype=str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [5]:
# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

[[1 3 0]
 [9 9 7]
 [3 6 1]]


In [6]:
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[[ 1.57345471 -0.77339248 -1.27483632]
 [ 0.10072122 -0.38061126  2.03648977]
 [-0.51553624  1.90622986 -2.09111917]]


Numpy는 다양한 형태로 합치기가 가능 있습니다.

In [7]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


Numpy를 위 아래로 합칠 수 있습니다.

In [8]:
import numpy as np

array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy의 형태를 변경할 수 있습니다.

In [9]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2.shape)

(2, 2)


Numpy의 형태를 나누기 할 수 있습니다.

In [10]:
import numpy as np

array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)

print(left.shape)
print(right.shape)
print(right[1][1])

(2, 2)
(2, 2)
7


기본 연산이 가능합니다.

In [11]:
# 두 배열 생성
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

# 사칙연산
print("덧셈:", arr1 + arr2)
print("뺄셈:", arr1 - arr2)
print("곱셈:", arr1 * arr2)
print("나눗셈:", arr1 / arr2)


덧셈: [11 22 33 44]
뺄셈: [ 9 18 27 36]
곱셈: [ 10  40  90 160]
나눗셈: [10. 10. 10. 10.]


배열 인덱싱 및 슬라이싱이 가능합니다.
- 배열 요소 접근 및 자르기

In [12]:
# 배열 생성
arr = np.array([10, 20, 30, 40, 50])

# 인덱싱
print("첫 번째 요소:", arr[0])
print("마지막 요소:", arr[-1])

# 슬라이싱
print("처음 3개 요소:", arr[:3])
print("중간 요소:", arr[1:4])


첫 번째 요소: 10
마지막 요소: 50
처음 3개 요소: [10 20 30]
중간 요소: [20 30 40]


배열 행렬 곱셈이 가능합니다
- 2차원 배열의 행렬 곱셈

In [13]:
# 2차원 배열 (행렬) 생성
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# 행렬 곱셈
result = np.dot(matrix1, matrix2)
print("행렬 곱셈 결과:\n", result)


행렬 곱셈 결과:
 [[19 22]
 [43 50]]


Numpy 기본 통계 연산이 가능합니다.
- 배열에서 평균, 합계, 최댓값, 최솟값 계산

In [14]:
import numpy as np

# 배열 생성
arr = np.array([10, 20, 30, 40, 50])

# 통계 연산
print("합계:", np.sum(arr))
print("평균:", np.mean(arr))
print("최댓값:", np.max(arr))
print("최솟값:", np.min(arr))


합계: 150
평균: 30.0
최댓값: 50
최솟값: 10
